- frappe_docs/www/docs/user/en/guides/basics/hooks.md
Documentation for https://github.com/frappe/frappe/pull/10549.
> docs: override whitelisted methods

- frappe_docs/www/docs/user/en/_sidebar.json
- frappe_docs/www/docs/user/en/core/router.md
This PR has the following changes
1. Added **Core** as group in sidebar
1. Add documentation for router
<details>
<summary>Screenshot</summary>
</details>
> feat: added router docs in core

- frappe_docs/www/docs/user/en/api/document.md
> docs: Update document API for tags usage

- frappe_docs/www/docs/user/en/guides/app-development/overriding-link-query-by-custom-script.md
> docs: Add info regarding decorator for search query

- frappe_docs/www/docs/user/en/api/form.md
merge after:
https://github.com/frappe/frappe/pull/11034
> feat: docs for cancel_all_enhancement

- frappe_docs/www/docs/user/en/api/form.md
**merge after**: https://github.com/frappe/frappe/pull/11034
> docs: ignore DocTypes during cancelation

- frappe_docs/www/docs/user/en/_sidebar.json
- frappe_docs/www/docs/user/en/api/full-text-search.md
- frappe_docs/www/docs/user/en/core/search.md
> feat: add docs and API reference for FTS

- README.md
> fix(README): Provide basic installation and contribution information

- frappe_docs/www/docs/user/en/debugging.md
> docs: Update execute capabilities

- frappe_docs/www/docs/user/en/python-api/hooks.md
Added docs for overriding Form Scripts
> docs(hooks): Overriding Form Scripts

- frappe_docs/www/docs/user/en/basics/doctypes/docfield.md
- frappe_docs/www/docs/user/en/debugging.md
Link to erpnext docs for details on list of DocFields
> fix: Fix broken links

- frappe_docs/www/docs/user/en/bench/guides/lets-encrypt-ssl-setup.md
Closes https://github.com/frappe/bench/issues/1090
> fix: Update user crontab + typo

- frappe_docs/www/docs/user/en/bench/frappe-commands.md
> docs: Updated bench list-apps

- frappe_docs/website_context.py
- frappe_docs/www/docs/user/en/bench/_sidebar.json
- frappe_docs/www/docs/user/en/bench/bench-commands.md
- frappe_docs/www/docs/user/en/bench/extending-the-cli.md
- frappe_docs/www/docs/user/en/bench/frappe-commands.md
- frappe_docs/www/docs/user/en/bench/index.md
- frappe_docs/www/docs/user/en/bench/reference/backup.md
- frappe_docs/www/docs/user/en/bench/reference/drop-site.md
- frappe_docs/www/docs/user/en/bench/reference/migrate.md
- frappe_docs/www/docs/user/en/bench/reference/new-site.md
- frappe_docs/www/docs/user/en/bench/reference/partial-restore.md
- frappe_docs/www/docs/user/en/bench/reference/reinstall.md
- frappe_docs/www/docs/user/en/bench/reference/restore.md
- frappe_docs/www/docs/user/en/bench/reference/uninstall-app.md
> docs: Site Commands Update

- frappe_docs/www/docs/user/en/api/py-dialog.md
Ref: https://github.com/frappe/frappe/pull/11711
> docs: as_list in msgprint

- frappe_docs/www/docs/user/en/basics/site_config.md
PR: https://github.com/frappe/frappe/pull/12183
> docs: new site config - allow_cors

- frappe_docs/www/docs/user/en/api/form.md
- frappe_docs/www/docs/user/en/api/index.md
- frappe_docs/www/docs/user/en/basics/doctypes/customize.md
- frappe_docs/www/docs/user/en/desk/scripting/client-script.md
- frappe_docs/www/docs/user/en/desk/scripting/index.md
- frappe_docs/www/docs/user/en/desk/scripting/server-script.md
- frappe_docs/www/docs/user/en/guides/app-development/overriding-link-query-by-custom-script.md
- frappe_docs/www/docs/user/en/guides/portal-development/generators.md
- frappe_docs/www/docs/user/en/guides/portal-development/web-forms.md
- frappe_docs/www/docs/user/en/web-forms.md
Related PR: https://github.com/frappe/frappe/pull/12324
> feat: Rename "Custom Script" to "Client Script"

- frappe_docs/www/docs/user/en/bench/frappe-commands.md
> docs: Set default site with FRAPPE_SITE

- frappe_docs/www/docs/user/en/python-api/hooks.md
> docs(hooks): Added docs for User Data Privacy

- frappe_docs/www/docs/user/en/bench/guides/setup-production.md
for https://github.com/frappe/bench/pull/1126
> docs(bench): setup supervisor without redis

- frappe_docs/www/docs/user/en/guides/reports-and-printing/getting-information-from-another-document-in-print-format.md
Remove grammatical errors and also fix broken code block.
> docs: Fix Reports and Printing docs

- frappe_docs/www/docs/user/en/api/form.md
> docs: frappe.whitelist for doc methods

- frappe_docs/www/docs/user/en/basics/doctypes/child-doctype.md
- frappe_docs/www/docs/user/en/basics/index.md
Fixes the path of broken images, introduced in https://github.com/frappe/frappe_docs/pull/100
> fix: broken image paths

- frappe_docs/www/docs/user/en/guides/integration/webhooks.md
- Added a line for letting the reader know about the new enable/disable feature.
- Fixed a small punctuation error.
> docs: Update Webhook docs

- frappe_docs/www/docs/user/en/python-api/hooks.md
hook for request authentication
Documentation for PR https://github.com/frappe/frappe/pull/12895
> docs: auth hooks

- frappe_docs/www/docs/user/en/api/rest.md
- frappe_docs/www/docs/user/en/guides/integration/how_to_set_up_oauth.md
- frappe_docs/www/docs/user/en/guides/integration/rest_api/oauth2.md
- frappe_docs/www/docs/user/en/guides/integration/rest_api/token_based_authentication.md
https://github.com/frappe/frappe/pull/12997
> docs: OAuth 2, PKCE, OIDC docs

- frappe_docs/www/docs/user/en/bench/_sidebar.json
- frappe_docs/www/docs/user/en/bench/frappe-commands.md
- frappe_docs/www/docs/user/en/bench/reference/list-apps.md
* Added list-apps reference page
* Added reference to bench sidebar
Docs for https://github.com/frappe/frappe/pull/12966
> fix: Updated bench list-apps -f json docs

- frappe_docs/www/docs/user/en/bench/_sidebar.json
- frappe_docs/www/docs/user/en/bench/frappe-commands.md
- frappe_docs/www/docs/user/en/bench/reference/set-config.md
- frappe_docs/www/docs/user/en/bench/reference/show-config.md
Added docs for 
- bench set-config
- bench show-config
Changes incorporated via https://github.com/frappe/frappe/pull/13102
> docs(cli): Added docs for set-config show-config

- frappe_docs/www/docs/user/en/bench/frappe-commands.md
- frappe_docs/www/docs/user/en/guides/automated-testing/unit-testing.md
- frappe_docs/www/docs/user/en/testing.md
- frappe_docs/www/docs/user/en/ui-testing.md
> docs: Add docs for run-parallel-tests command

- frappe_docs/www/docs/_sidebar.json
- frappe_docs/www/docs/user/en/basics/asset-bundling.md
- frappe_docs/www/docs/user/en/basics/static-assets.md
[View Rendered Page](https://user-images.githubusercontent.com/9355208/116809414-8a900500-ab5b-11eb-94d2-cf432046d08a.png)
> Asset bundling docs

- frappe_docs/www/docs/user/en/bench/frappe-commands.md
- frappe_docs/www/docs/user/en/bench/resources/bench-commands-cheatsheet.md
- frappe_docs/www/docs/user/en/python-api/hooks.md
Docs for https://github.com/frappe/frappe/pull/13180
> docs: ignored fields in fixtures

- frappe_docs/www/docs/user/en/api/controls.md
docs for https://github.com/frappe/frappe/pull/12847
> docs: add button api

- frappe_docs/www/docs/user/en/bench/_sidebar.json
- frappe_docs/www/docs/user/en/bench/frappe-commands.md
- frappe_docs/www/docs/user/en/bench/reference/bench-version.md
**Route:** /docs/user/en/bench/frappe-commands#display-version-of-installed-apps
**Route:** /docs/user/en/bench/reference/bench-version
Docs for https://github.com/frappe/frappe/pull/13640
> docs: `bench version --format`

- frappe_docs/www/docs/user/en/python-api/language.md
Update according to changes introduced by https://github.com/frappe/frappe/pull/13820
> docs: Update language resolution

- frappe_docs/www/docs/_sidebar.json
- frappe_docs/www/docs/user/en/api/database.md
- frappe_docs/www/docs/user/en/api/index.md
- frappe_docs/www/docs/user/en/api/query-builder.md
> docs: Frappe Query Builder

- frappe_docs/www/docs/user/en/api/controls.md
New Icon Picker Control https://github.com/frappe/frappe/pull/13676
> feat: Icon Picker Control Documentation

- frappe_docs/www/docs/user/en/basics/doctypes/fieldtypes.md
docs for https://github.com/frappe/frappe/pull/13707
> feat: Python Option in Code field type

- frappe_docs/www/docs/user/en/api/query-builder.md
* Added docs for method `run`
* Updated examples to use run instead
* Updated content to seem more fit/less confusing
> docs: Update QB execution

- frappe_docs/www/docs/user/en/bench/frappe-commands.md
- frappe_docs/www/docs/user/en/bench/resources/bench-commands-cheatsheet.md
---
documentation for https://github.com/frappe/frappe/pull/13868
> docs: autoreload for IPython

- frappe_docs/www/docs/user/en/ui-testing.md
> docs: Testing-Library queries

- frappe_docs/www/docs/user/en/installation.md
> docs: Installation on MacOS [M1]

- frappe_docs/www/docs/user/en/installation.md
- frappe_docs/www/docs/user/en/tutorial/create-a-doctype.md
* Fixed typo
* The dev mode doesn't get initialised if it is enabled while the server is running, so fixed that.
> docs: Update Install instructions, dev server restart & typo

- frappe_docs/www/docs/user/en/api/controls.md
docs for https://github.com/frappe/frappe/pull/13857
> docs: wrap-capability-in-code-editor

- frappe_docs/www/docs/_sidebar.json
- frappe_docs/www/docs/user/en/api/controls.md
- frappe_docs/www/docs/user/en/api/index.md
- frappe_docs/www/docs/user/en/api/scanner.md
<details>
<summary>Preview</summary>
<br>
</details>
Docs for https://github.com/frappe/frappe/pull/13855
> docs: Scanner API

- frappe_docs/www/docs/user/en/api/database.md
Documentation for `frappe.db.add_index` and changes in pr https://github.com/frappe/frappe/pull/14062
> docs: add_index

- frappe_docs/www/docs/user/en/api/form.md
- frappe_docs/www/docs/user/en/api/page.md
Docs for https://github.com/frappe/frappe/pull/14074
> docs: change custom button type api

- frappe_docs/www/docs/user/en/basics/apps.md
- frappe_docs/www/docs/user/en/bench/resources/bench-commands-cheatsheet.md
Docs for dev requirement setup feature.
https://github.com/frappe/bench/pull/1196
> docs: bench setup requirements --dev

- frappe_docs/www/docs/user/en/bench/frappe-commands.md
> docs: bench browse

- frappe_docs/www/docs/user/en/api/document.md
Docs for https://github.com/frappe/frappe/pull/13579
> docs: Convenience methods for NestedSet {get_parent, get_children}

- frappe_docs/www/docs/user/en/api/rest.md
docs for https://github.com/frappe/frappe/pull/15103
> docs(REST): OR filters
