frappe/frappe_docs

frappe_docs/www/docs/user/en/guides/basics/hooks.md

docs: additional_timeline_content

---

frappe_docs/www/docs/user/en/api/dialog.md

Update python API for `msgprint` and `throw`
ref: https://github.com/frappe/frappe/pull/11190

feat: update dialog arguments

---

frappe_docs/www/docs/user/en/api/form.md

Reverts frappe/frappe_docs#25
The feature PR https://github.com/frappe/frappe/pull/11034 was not merged yet.

Revert "feat: docs for cancel_all_enhancement"

---

frappe_docs/website_context.py

Right now, we don't have a Twitter handle for the Frappe Framework, but we do have one for [@frappetech](https://twitter.com/frappetech). So I think we can use that, until we get one for [@frappeframework](https://twitter.com/frappeframework) ?

fix: Twitter Handle

---

frappe_docs/www/docs/user/en/guides/integration/rest_api/oauth2.md

`authorize` it supposed to be called by the user directly, via his browser. Therefore, a `GET` request is more appropriate here.
See also: https://discuss.erpnext.com/t/oauth-profile-error/65031/16?u=rmeyer .

fix: oauth2 authorize

---

frappe_docs/www/docs/user/en/guides/basics/sites.md

Changed "you site" to "your site" under apps.txt subheading.

fix: typo in sites.md

---

frappe_docs/www/docs/user/en/api/py-dialog.md
frappe_docs/www/docs/user/en/basics/site_config.md
frappe_docs/www/docs/user/en/bench/bench-commands.md

bench config set-common-config or remove-comon-config need 'configs', '-c', '--config' to send config value
line 53 of bench/commands/config.py
`@click.command('set-common-config', help='Set value in common config')
@click.option('configs', '-c', '--config', multiple=True, type=(str, str))
def set_common_config(configs):`
If this option is not provided, there is error 
for exemple 
```
$bench config set-common-config enable_frappe_logger true
Error: Got unexpected extra argument (enable_frappe_logger)
```
but 
`$bench config set-common-config -c enable_frappe_logger true`
is ok
**Changes**
- Fixed command usage
- Added examples for bench config updation

fix: bench config set-common-config documentation

---

frappe_docs/www/docs/user/en/basics/directory-structure.md
frappe_docs/www/docs/user/en/basics/doctypes/controllers.md
frappe_docs/www/docs/user/en/bench/bench-commands.md
frappe_docs/www/docs/user/en/bench/frappe-commands.md
frappe_docs/www/docs/user/en/desk/index.md
frappe_docs/www/docs/user/en/installation.md
frappe_docs/www/docs/user/en/production-setup.md
frappe_docs/www/docs/user/en/python-api/search.md
frappe_docs/www/docs/user/en/translations.md
frappe_docs/www/docs/user/en/tutorial/types-of-doctype.md

Summary of changes:
- remove default mariadb configs for Arch linux installation guide: 
Removed config are now default in mariadb, Ref: https://mariadb.com/kb/en/innodb-system-variables/
- add mysql charset config in mac install. 
This was recommended in other installation guides on frappe/bench wiki.
- fix broken link to apps section
- fix link for frequent commands
- fix broken link to WebsiteSearch.py file
- Desktop is now Workspace, changed link and text: 
Refer commit 36cbbf2d and discussion on erpnext forums: https://discuss.erpnext.com/t/redesigning-desk/59105
- fix link to easy install script
- Remove google translate toolkit and linking to homepage: 
Google translate toolkit was shutdown last year. Ref:  https://support.google.com/answer/9464390
- Update homebrew install …

docs: Minor doc fixes

---

frappe_docs/www/docs/user/en/api/dialog.md

As requested by barredterra in the discussion to this frappe issue:
https://github.com/frappe/frappe/issues/7638
I put the documentation for this on the Dialog API page because it
seemed to me that in the context of its use in client-side code,
frappe.new_doc() does primarily serve as a means of creating a
user dialog, specifically for the creation of a new document.
Docs for https://github.com/frappe/frappe/pull/11900

docs: document frappe.new_doc()

---

frappe_docs/www/docs/user/en/api/form.md

Issue - didn't found the function clear_custom_button

replacing clear_custom_button to remove_custom_button

---

frappe_docs/www/docs/user/en/bench/resources/bench-commands-cheatsheet.md

Previous help message was misleading.  
Ref: https://github.com/frappe/bench/pull/1116

docs: update doc for --frappe-branch flag

---

frappe_docs/www/docs/user/en/installation.md

Fixes #97 
The default Ubuntu 20.04 repository includes MariaDB 10.3 package (which is required by Frappe while) while Ubuntu 18.04's default repository has MariaDB 10.1. So, the external PPA should not be added in Ubuntu 20.04. 
If the external PPA repository is added to Ubuntu 20.04 system, it causes conflicting issues while MariaDB installation.

docs: Update MariaDB installation instructions for Ubuntu

---

frappe_docs/www/docs/_sidebar.json
frappe_docs/www/docs/user/en/desk/reports/index.md

Fix the links for query, script, and report builder pages.
Fixes #110

fix: broken report links

---

frappe_docs/www/docs/user/en/desk/scripting/index.md

Fixes the broken `Script Report` link on Scripting page https://frappeframework.com/docs/user/en/desk/scripting.
Reported in https://github.com/frappe/frappe_docs/issues/110

fix(scripting): broken link for script-report

---

frappe_docs/www/docs/user/en/desk/scripting/server-script.md

When I try to make a request to "api/method/test_method" we got an error in custom script because then it generates /server/api/method/api/method/test_method". 
It should be made to "test_method" in custom script. I am not sure about the custom apps.

For API type, request should be made to "test_method"

---

frappe_docs/www/docs/user/en/bench/bench-commands.md

For PR: https://github.com/frappe/bench/pull/1161
The `set-default-site` command is being removed from the `bench`.
The `bench use <site>` command should be used for setting the default site.

chore: Remove deleted command's docs

---

frappe_docs/www/docs/user/en/python-api/hooks.md

The closing quote of the value of `update_website_context` was broken.

Fixed broken quote in hooks.md

---

frappe_docs/www/docs/user/en/api/database.md
frappe_docs/www/docs/user/en/api/jinja.md

Added info about: 
1. the `pluck` kwarg
2. what happens when the `fields` kwarg is not passed
Also, added an example that shows the use of above.

docs: Add fields and pluck kwargs info

---

frappe_docs/www/docs/user/en/tutorial/types-of-doctype.md

`article.status == "Issued"` to `article.status = "Issued"`

docs: Fix typo in Tutorial

---

frappe_docs/www/docs/user/en/api/database.md

The name of the second argument to `frappe.db.sql` is `values`. It was incorrectly mentioned as `filters`.

fix: corrected the name of argument to frappe.db.sql

---

frappe_docs/www/docs/user/en/python-api/hooks.md

Add a note about the migration of scheduled jobs in `hooks.py`
Avoids confusion like : https://discuss.erpnext.com/t/hooks-py-updated-but-scheduled-job-not-running/75437

docs: note about scheduled job migration

---

frappe_docs/www/docs/_sidebar.json
frappe_docs/www/docs/user/en/api/index.md
frappe_docs/www/docs/user/en/api/utils.md

Add docs for must-know **Python utility functions** available in Frappe Framework. This function docs include datetime utilities, PDF generation, cache, string formatting, validations and **more**.

docs: Common Python Utility Functions

---

frappe_docs/www/docs/user/en/api/form.md

Sometimes some manipulations doesn't set form as dirty so frm.dirty() method should be documented.

docs: Form dirty API

---

frappe_docs/www/docs/user/en/basics/doctypes/controllers.md

Added `before_update` and `after_update` methods to list of controller hooks.

docs: adds controller hooks for rename

---

frappe_docs/www/docs/user/en/portal-pages.md

- added description for safe_render

fix: Docs for frontmatter blocks and context keys

---

frappe_docs/www/docs/user/en/installation.md

- Brew on Apple M1 needs Rosetta2: https://stackoverflow.com/a/64997047
- `--cask` option: https://stackoverflow.com/q/30413621
- https://github.com/creationix/nvm redirects to https://github.com/nvm-sh/nvm
Installation is still not working for me, but I believe these updated instructions are a step closer to the goal.

docs: install on mac

---

frappe_docs/www/docs/user/en/api/database.md

Updated documentation for database API
* Updated usages of `frappe.db.delete`
* Added `frappe.db.truncate`
Docs for https://github.com/frappe/frappe/pull/13753

docs: Updated Database API

---

frappe_docs/www/docs/user/en/installation.md
frappe_docs/www/docs/user/en/production-setup.md

Docs relate to the Redis namespaces introduced in PR https://github.com/frappe/frappe/pull/13746 .

docs: Redis namespaces

---

frappe_docs/www/docs/user/en/installation.md

Mac - Installation on 10.6 fails, while the [support for it is underway](https://github.com/frappe/frappe/pull/13954); old versions will likely not get it. Hence safe bet is to recommend installing 10.5.
Linux - 10.3 is suggested, so not a problem

fix: change installation command to mariadb 10.3

---

frappe_docs/commands.py
frappe_docs/www/docs/user/en/bench/_sidebar.json
frappe_docs/www/docs/user/en/bench/extending-the-cli.md
frappe_docs/www/docs/user/en/bench/frappe-commands.md
frappe_docs/www/docs/user/en/bench/index.md
frappe_docs/www/docs/user/en/bench/reference/__init__.py
frappe_docs/www/docs/user/en/bench/reference/_sidebar.json
frappe_docs/www/docs/user/en/bench/reference/index.md
frappe_docs/www/docs/user/en/bench/reference/transform-database.md
frappe_docs/www/docs/user/en/bench/reference/trim-database.md
frappe_docs/www/docs/user/en/bench/reference/trim-tables.md

- Removed command references from CLI sidebar. Moved into a separate page (index)
- Added command to make it easier to write command references using a template: `bench add-command-reference [COMMAND]` in frappe_docs.
- Added docs for https://github.com/frappe/frappe/pull/13954
- bench db-console
- bench transform-database
- Added docs for https://github.com/frappe/frappe/pull/13955
- trim-tables
- trim-database

docs: Update Bench Commands

---

frappe_docs/www/docs/user/en/api/form.md

Docs on child table events were wrong ([since 2016, it seems](https://discuss.erpnext.com/t/solved-cant-trigger-child-table--add-or--remove-events/15024/4?u=rmeyer) 😕 ).
The event functions need to be attached to the child doctype, not the parent doctype.

docs: fix docs of child table events

---

frappe_docs/www/docs/user/en/basics/site_config.md
frappe_docs/www/docs/user/en/guides/database-settings/setup-read-from-secondary-db.md

Docs for frappe pr https://github.com/frappe/frappe/pull/14159 added in /docs/user/en/basics/site_config and /docs/user/en/guides/database-settings/setup-read-from-secondary-db

feat: custom database port for read-only replica configuration

---

frappe_docs/www/docs/user/en/guides/automated-testing/qunit-testing.md

This PR will fix the [qunit-testing](https://frappeframework.com/docs/user/en/guides/automated-testing/qunit-testing) broken page.
---
fixes: https://github.com/frappe/frappe_docs/issues/148

fix: add `safe_render` flag in `qunit-testing`

---

frappe_docs/www/docs/user/en/bench/resources/bench-commands-cheatsheet.md
frappe_docs/www/docs/user/en/testing.md

docs for https://github.com/frappe/bench/pull/1218 (and subset of https://github.com/frappe/frappe/pull/15028)

docs: no-git option in bench new-app command and provide input while testing commands

---

frappe_docs/www/docs/user/en/basics/doctypes/naming.md

A new section and table have been added describing all available
placeholders. This also includes the newly introduced placeholder for
the consecutive calendar week (`WW`).
See: https://github.com/frappe/frappe/pull/14514

docs: add info about placeholders for naming series
